server:
   port: 8087
druid:
  allow:
     ip: 127.0.0.1
  login:
     user_name: root
     password: root

dubbo:
  application:
    name: user-app
  #  qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 47.57.72.11:3320

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20882
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000

#  metadata-report:
#    # 注册中心协议
#    protocol: zookeeper
#    # 注册中心地址
#    address: 127.0.0.1:2181
spring:
 main:
   allow-bean-definition-overriding: true
#spring.main.allow-bean-definition-overriding=true