server:
   port: 8087
druid:
  allow:
     ip: 127.0.0.1
  login:
     user_name: root
     password: root

dubbo:
  application:
    name: user-app
  #  qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 47.57.72.11:3320

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20882
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000

#  metadata-report:
#    # 注册中心协议
#    protocol: zookeeper
#    # 注册中心地址
#    address: 127.0.0.1:2181
spring:
  main:
    allow-bean-definition-overriding: true
#spring.main.allow-bean-definition-overriding=true
  datasource:
    url: jdbc:mysql://47.57.72.11:3306/shop
    username: root
    password: a123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-idle: 5
    max-wait-millis: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
    configuration:
   #开启驼峰
      map-underscore-to-camel-case: true
   #开启sql日志
      logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
   level:
       root: info
   name: coupon-userapp
